### PR TITLE
Nearby collapse

### PR DESCRIPTION
**Pull request by polanpio**
I've added a collapse effect to nearby section. Potential problem - it collapse the whole section, so you don't see a preview of first three pets. Should I work on it?

### CODE REVIEW

**Comment by polanpio** [comment]
nearby_collapse

**Comment by ellie-xyb** [comment]
Nice! I was thinking about this design, I think the nearby section is the most important and should probably be open always. This is because you wouldn't want to look after a pet that is more than an hour away. Maybe the all section can collapse instead?

Other than the "all" section collapsing, we could also have a distance bar that changes the search distance settings. This would mean we can just have one section.

Screen Shot 2021-07-26 at 19 52 13

It could go from <2km up to "all", with a few options in the middle. What do you think of these two ideas?

**Comment by polanpio** [comment]
I agree about nearby section. It should be always visible at least 3 or 6 options. That’s why I wasn’t really sure about collapse I made -__- Filter for the distance would be a nice addition too!

It feels like both nearby and all should initially show you a few options which then you could control with ‘show more’ or something similar.

**Comment by polanpio** [comment]
5A1D5FE9-06E5-4617-B201-73066F291186

**Comment by polanpio** [comment]
Something like this but with our pet cards.

**Comment by ellie-xyb** [comment]
For me, I think one section with a distance filter bar is the best option, but I am also OK with having two sections. In that case, as you said, both should show at least 3 or 6 options, with either 'collapse' or 'show more'.

**Pull request merged**
