### PR TITLE
Update seeds

### PR DESCRIPTION
**Pull request by ellie-xyb**
I created 3 pet seeds with a picture using Cloudinary.
Also created _card.scss in components. 
Added a .pet-card class as a placeholder.

### CODE REVIEW

**Review by polanpio — COMMENTED** [review]
for the species column, should we have things like cat,dog etc., so we can filter easier later and the thing like breed would be another column, without validation for presence?

**Comment by ellie-xyb** [comment]
Okay! I will change the species column and add a breed column too, also I'll add more seeds in the same way.

**Comment by ellie-xyb** [comment]
It's updated.

**Review by polanpio — COMMENTED** [review]
looks like everything is OK! good to merge

**Pull request merged**
