### PR TITLE
Navbar footer

### PR DESCRIPTION
**Pull request by polanpio**
I have finally did it! Grass animation on landing page is working. I will post a gif so you can see ;)

### CODE REVIEW

**Comment by polanpio** [comment]
dog_head
pettu_logo

**Comment by ellie-xyb** [comment]
The logo  & favicon looks so good on the app! That grass animation is really cool :)  

Seems the button on the rightside of banna doesn't work .
Screen Shot 2021-07-31 at 8 25 01

**Comment by polanpio** [comment]
Oh, I didn’t touch it Selim said it was working..

**Review by ellie-xyb — APPROVED** [review]
This one is ready to merge:)

**Pull request merged**
