### PR TITLE
Map feature

### PR DESCRIPTION
**Pull request by polanpio**
I've added a map, working distance feature and customized marker for a map. 
I would love to fix thee marker a little more, but it can't wait for later ;)

### CODE REVIEW

**Comment by polanpio** [comment]
distance
marker

**Comment by ellie-xyb** [comment]
WOW! This looks so good! Thanks for adding this cool feature. The code looks good to me!

**Review by ellie-xyb — APPROVED** [review]
The code looks good to me! Please merge anytime:)

**Comment by polanpio** [comment]
Cool! I’ll marge this one then. I’m working on show redesign now

**Pull request merged**
