### PR TITLE
Nearby section

### PR DESCRIPTION
**Pull request by polanpio**
I added nearby feature, filter works with it too ;) The only problem I see us that the pet's in nearby are the same as the one in a big list, but that might be obvious only because we have only 10 pets. See All button is not working yet, will work on it later.

### CODE REVIEW

**Comment by polanpio** [comment]
I guess we can move some code from erb files to controller...

**Comment by ellie-xyb** [comment]
It gave me an error message when I run rails db:seed,  will fix the problem by replacing line  11, 12 in seeds.rb to 
```
Booking.destroy_all
PetSchedule.destroy_all
Pet.destroy_all
User.destroy_all
```

**Comment by polanpio** [comment]
I had that problem already when I was doing the map. I added the right association that when you destroy the pet it destroys the bookings too (or other way around). Anyway I will add it with next commit.

**Comment by ellie-xyb** [comment]
Thank you for doing so much!  
The code looks good, merge it whenever:)

**Review by ellie-xyb — APPROVED** [review]

**Pull request merged**
