### PR TITLE
Landing page

### PR DESCRIPTION
**Pull request by polanpio**
Most of the landing page is done. Still need to add a few animations.

### CODE REVIEW

**Comment by polanpio** [comment]
for the conflict in application.js, I've added a class to our original carousel to distinguish it from the one on landing page, I'm not sure how it goes with your code though..

**Comment by polanpio** [comment]
yarn.lock conflict, I have no idea what is it about, different versions of something?

**Comment by polanpio** [comment]
conflict in _index solved, we had repeating import for owl-carousel

**Comment by ellie-xyb** [comment]
WOW!  This landing page is AMAZING!!!
Only see two small things we can change: 
-Find a pet button is hard to see.
-Footer is not sticky on other pages.

Very minor we can consider them in another pr. I think this one is OK to merge:)

**Review by ellie-xyb — APPROVED** [review]

**Pull request merged**
